development:
  adapter: postgresql
  encoding: unicode
  database: jamlister_development
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: jamlister_production
  pool: 5
  username: postgres
  password:
