development:
  adapter: postgresql
  encoding: unicode
  database: jamlister
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: jamlister
  pool: 5
  username: postgres
  password:
